yarnPath: ".yarn/releases/yarn-berry.cjs"

packageExtensions:
  "markdown-it@*":
    dependencies:
      punycode: latest
  tinacms@*:
    dependencies:
      final-form: ^4.18.2
      prop-types: ">=15"
      react-beautiful-dnd: ^11.0.5
      react-dismissible: ^1.3.0
  # Plate editor
  '@udecode/plate-csv-serializer@*':
    dependencies:
      slate-history: latest
  "@udecode/plate-mention@*":
    peerDependencies:
      styled-components: latest
  "next-tinacms-cloudinary@*":
    dependencies:
      "@tinacms/toolkit": latest
