yarnPath: ".yarn/releases/yarn-berry.cjs"

packageExtensions:
  # Attempt at getting markdown editor loading, what a disaster
  # "markdown-it@*":
  #   dependencies:
  #     punycode: latest
  # "react-tinacms-inline@*":
  #   dependencies:
  #     prop-types: ">=15"
  #     final-form: ^4.18.2
  #     "@tinacms/icons": latest
  #     "@tinacms/styles": latest
  #     "@tinacms/fields": latest
  #     "@tinacms/form-builder": latest
  #     "@tinacms/react-core": latest
  #     "@tinacms/react-forms": latest
  #     react-beautiful-dnd: ^11.0.5
  #     react-dismissible: ^1.3.0
  #     react-tinacms-inline: latest
  # "react-tinacms-editor@*":
  #   dependencies:
  #     prop-types: ">=15"
  #     final-form: ^4.18.2
  #     "@tinacms/icons": latest
  #     "@tinacms/styles": latest
  #     "@tinacms/fields": latest
  #     react-dropzone: latest
  #     "@tinacms/form-builder": latest
  #     "@tinacms/react-core": latest
  #     "@tinacms/react-forms": latest
  #     react-final-form: latest
  #     react-beautiful-dnd: ^11.0.5
  #     react-dismissible: ^1.3.0
  #     react-tinacms-inline: latest
  # "@tinacms/fields@*":
  #   peerDependencies:
  #     "@tinacms/form-builder": latest
  #     "@tinacms/icons": latest
  #     "@tinacms/react-core": latest
  #     "@tinacms/react-forms": latest
  #     "@tinacms/styles": latest
  #     prop-types: ">=15"
  #     react-beautiful-dnd: ^11.0.5
  #     react-dismissible: ^1.3.0
  # "@tinacms/form-builder@*":
  #   peerDependencies:
  #     final-form: ^4.18.2
  #     react-beautiful-dnd: ^11.0.5
  #     react-dom: ^16.13.0
  #     react-dismissible: ^1.3.0
  # "@tinacms/icons@*":
  #   peerDependencies:
  #     react: ^16.13.0
  # "@tinacms/react-forms@*":
  #   peerDependencies:
  #     final-form: ^4.18.2
  #     prop-types: ">=15"
  # "@tinacms/react-toolbar@*":
  #   peerDependencies:
  #     react-beautiful-dnd: ^11.0.5
  #     react-dom: ^16.13.0
  # "@tinacms/styles@*":
  #   peerDependencies:
  #     react: ^16.13.0
  tinacms@*:
    dependencies:
      final-form: ^4.18.2
      prop-types: ">=15"
      react-beautiful-dnd: ^11.0.5
      react-dismissible: ^1.3.0
