fragment LocaleInfoParts on LocaleInfo {
  au {
    __typename
    tel
    signUpLink
    signUpLinkPersonal
    signInLink
  }
  us {
    __typename
    tel
    signUpLink
    signUpLinkPersonal
    signInLink
  }
  gb {
    __typename
    tel
    signUpLink
    signUpLinkPersonal
    signInLink
  }
}

fragment NewsParts on News {
  title
  subTitle
  description
  image
  body
}

fragment FooterParts on Footer {
  offices {
    __typename
    location
    address
    phone
  }
  disclaimers {
    __typename
    body
  }
}

fragment ThemeParts on Theme {
  displayFont
  colorMode
}

fragment NavigationParts on Navigation {
  items {
    __typename
    page {
      ... on Document {
        id
      }
    }
  }
}

fragment PageParts on Page {
  title
  link
  seo {
    __typename
    title
    image
    description
  }
  blocks {
    __typename
    ... on PageBlocksNews {
      title
      subTitle
      description
      newsItems {
        __typename
        article {
          ... on Document {
            id
          }
        }
      }
    }
    ... on PageBlocksStatsWithImage {
      title
      subTitle
      description
      image
      stats {
        __typename
        title
        subTitle
        description
      }
    }
    ... on PageBlocksHero {
      title
      subTitle
      description
      style
      image
      action {
        __typename
        callToAction
        linkText
        link
        linkOverride
        secondaryText
        secondaryLink
        secondaryLinkOverride
      }
    }
    ... on PageBlocksSlideshow {
      items {
        __typename
        title
        subTitle
        description
        image
        textColor
        action {
          __typename
          callToAction
          linkText
          link
          linkOverride
          secondaryText
          secondaryLink
          secondaryLinkOverride
        }
        overlayColor
        overlayOpacity
      }
    }
    ... on PageBlocksComparisonTable {
      title
      subTitle
      description
      items {
        __typename
        title
        subTitle
        description
        bulletPoints
      }
      action {
        __typename
        callToAction
        linkText
        link
        linkOverride
        secondaryText
        secondaryLink
        secondaryLinkOverride
      }
    }
    ... on PageBlocksFullScreenLogo {
      slogan
      link
      image
      textColor
      overlayColor
      overlayOpacity
    }
    ... on PageBlocksFullScreenHeader {
      title
      subTitle
      description
      action {
        __typename
        callToAction
        linkText
        link
        linkOverride
        secondaryText
        secondaryLink
        secondaryLinkOverride
      }
      image
      textColor
      overlayColor
      overlayOpacity
    }
    ... on PageBlocksFeature {
      title
      subTitle
      description
      featureStyle
      features {
        __typename
        icon
        name
        description
      }
      image
      textColor
      overlayColor
      overlayOpacity
    }
    ... on PageBlocksScreenShotFeature {
      title
      subTitle
      description
      image
      alignment
      icon
      action {
        __typename
        callToAction
        linkText
        link
        linkOverride
        secondaryText
        secondaryLink
        secondaryLinkOverride
      }
      testimonial {
        __typename
        quote
        author {
          __typename
          name
          avatar
        }
      }
    }
  }
}
